### ISSUE TITLE
Error with fresh setup of stable version

### ISSUE THREAD

**Issue by MathiasRenner** [powertac/powertac-server#1036] opened 2019-12-03 16:59 UTC
Following the docs [here in github](https://github.com/powertac/server-distribution) and [here on the wiki](http://www.powertac.org/wiki/index.php/Getting_Started) a fresh setup on a Debian based Linux looks like this:

----
#### Prepare
* sudo apt install maven
* mvn -version (installs v3.6.0)
* sudo apt install default-jdk (installs v11)
* sudo apt install git

#### Run latest stable version
* git clone --branch release-1.6 https://github.com/powertac/sample-broker.git
* cd sample-broker
* mvn clean test 
* mvn test exec:exec

-----

However, the last command results in an exception:

```
Starting session 1
  name=Sample
Exception in thread "main" java.lang.IllegalArgumentException: Property 'connectionFactory' is required
	at org.springframework.jms.support.JmsAccessor.afterPropertiesSet(JmsAccessor.java:169)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.afterPropertiesSet(AbstractJmsListeningContainer.java:165)
	at org.powertac.samplebroker.core.JmsManagementService.registerMessageListener(JmsManagementService.java:112)
	at org.powertac.samplebroker.core.PowerTacBroker.run(PowerTacBroker.java:260)
	at org.powertac.samplebroker.core.PowerTacBroker.startSession(PowerTacBroker.java:185)
	at org.powertac.samplebroker.core.BrokerRunner.processCmdLine(BrokerRunner.java:173)
	at org.powertac.samplebroker.core.BrokerMain.main(BrokerMain.java:39)
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```

How can I resolve this?

**Comment by jecollins** [comment] 2019-12-03 17:48
This is very curious. The 1.6.0 sample-broker works just fine under Java 8, following the instructions described in this issue. Under Java 11, the problem is easy to confirm.

So the question is whether it's worth a fix, since the 1.7.0-SNAPSHOT broker works fine under Java 11, and it would take a significant effort to determine exactly which library upgrade would be required to resolve this problem. The problem is clearly in powertac-core and not in sample-broker. The changes in powertac-core include a version upgrade to the apachemq jms library, which may be related.

Note that broker-core on the current master branch still suffers from Issue #1029 when sample-broker is run from a jar file. This is fixed on the java11 branch, not yet merged.

**Comment by MathiasRenner** [comment] 2019-12-03 18:23
@jecollins Thanks for your feedback! I am not focused on v 1.6 on purpose, I am happy with any working version.
Where do I find the 1.7 release? There's no tag for that.

(p.s. yes, I tried the latest master, too, resulting in dependency errors)

**Comment by jecollins** [comment] 2019-12-03 18:29
Interesting - thanks for the feedback. The master branch is supposed to work. I still have stuff on my java11 branch, reluctant to merge just yet since it will almost certainly break for folks still on Java 8. Let me do a little checking to see if there's a quick fix for you.

**Comment by MathiasRenner** [comment] 2019-12-03 18:32
Nice!
That was the error using latest master branch, might help for you:

`
Could not resolve dependencies for project org.powertac:sample-broker:jar:1.7.0-SNAPSHOT: Could not find artifact org.junit.jupiter:junit-jupiter:jar:5.3.1 in sonatype (https://oss.sonatype.org/content/repositories/snapshots/...
`

Interestingly, it says "1.7.0" even there is not git tag for that.

**Comment by jecollins** [comment] 2019-12-04 01:07
At this point, the master branch of powertac-core requires Java11, but that requirement is not in the version that is currently deployed to the Sonatype snapshot repo. I thought it would be enough to delay the deployment, but it appears I've been lazy. The deployed version includes a master pom.xml that specifies 5.3.1 as the version for the junit modules. But in that version, the jupiter module was called junit-jupiter-engine instead of just junit-jupiter. Meanwhile, the [pom.xml for sample-broker was updated to build under Java 11](https://github.com/powertac/sample-broker/commit/47b1b49d76747d010b060495acc2b1ef18979949). It works with the current master branch of powertac-core, but not with the older deployed version.

So it seems there are two possible approaches to resolving this:

* Reset the master branch of sample-broker to before this issue was introduced, or
* Use a local installed version of broker-core to build sample-broker in a Java 11 environment. This is done by cloning (or downloading) [powertac-core](https://github.com/powertac/powertac-core), and then installing it (mvn clean install). This works in a Java 11 environment, and the local install will override the current deployed version.

**Comment by jecollins** [comment] 2019-12-07 17:56
I plan to deploy the Java 11 updates to the Sonatype snapshot repo early next week (9 or 10 December 2019). In the meantime, one additional update has been pushed to the master branch of powertac-core that solves Issue #1029 in which the broker would not run correctly from a jar file.

**Comment by MathiasRenner** [comment] 2019-12-10 11:10
> I plan to deploy the Java 11 updates to the Sonatype snapshot repo early next week (9 or 10 December 2019). In the meantime, one additional update has been pushed to the master branch of powertac-core that solves Issue #1029 in which the broker would not run correctly from a jar file.

@jecollins Nice. I could test the Sonatype update in about 3 hours. Do you expect have that merged until then?

**Comment by jecollins** [comment] 2019-12-10 20:00
This issue should now be resolved with the deployment of the Java-11 compliant server. I apologize for committing the associated changes to the broker prematurely, about two weeks ago.

**Closed by jecollins** 2019-12-10 20:00 UTC
Labels: Broker

**Comment by MathiasRenner** [comment] 2019-12-11 09:18
Error is gone, thanks!

**Comment by Sanjay-14BIT009** [comment] 2020-01-03 06:44
Sorry to write in closed issue, but I'm facing the same problem.

I am able to run **sample-broker 1.7.0** without any problem with 1.7 version of server.

But I'm getting the same error while running **sample-broker 1.6.0** with **Power TAC distribution 1.7.0-SNAPSHOT**. Our broker is built upon **sample-broker 1.6.0** , so it is also throwing the same error.

I tried local install of powertac-core as you said in one of the comments, but it didn't help.

**Software Configurations:**
**JAVA** : java version "11.0.5" 2019-10-15 LTS
**Maven** : Apache Maven 3.6.0

Kindly help me to resolve this issue.
