### ISSUE TITLE
Visualizer 2 cannot run sim sessions

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#890] opened 2016-08-05 16:48 UTC
This is apparently a platform-dependent bug; it works for Erik but not for me. Here's what I see in the console when I poke Start on a sim session:

```
Exception in thread "Thread-26" java.lang.NoSuchMethodError: org.apache.activemq.transport.TransportFactory.bind(Lorg/apache/activemq/broker/BrokerService;Ljava/net/URI;)Lorg/apache/activemq/transport/TransportServer;
	at org.apache.activemq.broker.BrokerService.createTransportConnector(BrokerService.java:2249)
	at org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:291)
	at org.apache.activemq.broker.BrokerService.addConnector(BrokerService.java:281)
	at org.powertac.server.JmsManagementService.startProvider(JmsManagementService.java:98)
	at org.powertac.server.JmsManagementService.start(JmsManagementService.java:79)
	at org.powertac.server.CompetitionControlService.runOnce(CompetitionControlService.java:295)
	at org.powertac.server.CompetitionSetupService$2.run(CompetitionSetupService.java:579)
```

**Comment by erikkemperman** [comment] 2016-09-12 11:26
Just for posterity: this is caused by versions mismatch in activemq components, and should be resolved when the dependency bump (along with proposed module restructuring) is landed.

**Comment by erikkemperman** [comment] 2016-09-15 10:52
@jecollins This should be resolved with the latest round of merges, which align (and upgrade) activemq versions.

**Closed** 2016-09-25 15:49 UTC
