### ISSUE TITLE
server-distribution is throwing an error while running games using finals2021 boot files

### ISSUE THREAD

**Issue by Sanjay-14BIT009** [powertac/powertac-server#1106] opened 2021-11-20 05:45 UTC
Server-distribution is throwing an ArrayIndexOutOfBoundsException when it is used to run games using finals2021 boot-files, the broker does not connect and the game eventually terminates. However,  it is working fine while running the games using finals2019 boot-files.

command: mvn -Pcli -Dexec.args="--sim --boot-data finals_2021/finals_2021_1.xml --weather-data finals_2021/log/finals_2021_1.state --brokers Sample"

server-distribution version: 1.9.0-SNAPSHOT

Error-logs:
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 1
        at org.powertac.server.WeatherService$StateFileExtractor.extractData(WeatherService.java:739)
        at org.powertac.server.WeatherService$WeatherRequester.run(WeatherService.java:306)
        at org.powertac.server.WeatherService.activate(WeatherService.java:189)
        at org.powertac.server.CompetitionControlService.step(CompetitionControlService.java:794)
        at org.powertac.server.CompetitionControlService$SimRunner.run(CompetitionControlService.java:1131)

**Comment by jecollins** [comment] 2021-11-20 20:48
Did this happen right away or at the end? When you run a new game this way, it's possible for the new game to be longer than the game from which you are extracting weather data, in which case you would indeed see an error like this at the point where the new game ran off the end of the weather data from the old game. It's possible to specify the exact length of a game by setting the property competition.fixedTimeslotCount

**Comment by Sanjay-14BIT009** [comment] 2021-11-21 11:15
Thanks for the response. This is happening at the start of the game (actually the game doesn't start) every time I use finals2021 boot files. Strangely, I am able to run full games (~1400 timeslots) using finals2019 boot files, no exception occurs in those games. 
If I don't provide --weather-data in the command, the game doesn't start for any of the boot files (finals2019 or finals2021).

**Comment by jecollins** [comment] 2021-11-27 22:00
The problem is that [since 1.7.0](https://www.powertac.org/wiki/index.php/Release_History#Release_notes_1.7.0), the server writes out a metadata prefix to the state log, and the weather service was not updated to skip over that. This is compounded by the fact that our test suite does not test this feature, and apparently it has not been used in over a year.

**Comment by jecollins** [comment] 2021-11-28 15:26
Command-line args permit both weather data and random-seed data to be retrieved from existing state files. There are now three different formats for state files:
1. The original format
2. Metadata format -- original format prefixed with the metadata block
3. Abbreviated metadata format -- compact metadata format in which classnames are abbreviated. org.powertac prefix is omitted, org.powertac.common prefix is abbreviated to just "c"
So we need to test both weather data and random seed data loading with all three formats.

**Comment by jecollins** [comment] 2021-11-28 15:51
Currently, we are reading state logs in three different places:

- org.powertac.logtool.LogtoolCore
- org.powertac.server.WeatherService
- org.powertac.common.repo.RandomSeedRepo

Therefore we have to update all three when we change/enhance the log format. This is crazy, especially given that LogtoolCore.readStateLog() is designed to be able to extract any type of data desired from a state log, including logs embedded in .tar and .tgz archives.

**Comment by jecollins** [comment] 2021-11-28 16:10
This issue will require some refactoring to avoid piling on additional technical debt. Until that's done, here's a workaround:

1. If the first line of the state log does not contain the string "Domain-schema-version", then it's an older log. Seed and weather extraction should work correctly.
1. If the first line of the state log contains the string "Domain-schema-version", then scroll down to the line containing "schema.end" and check the next line. If it contains "c.Competition", then it's abbreviated and you will not be able to extract seed and weather data. Don't use it.
2. Otherwise, strip off the metadata prefix starting with the "Domain-schema-version" line down to and including the line containing "schema.end". The resulting file should work correctly for extracting random seeds and weather data. It may no longer work to re-play games.

**Comment by Sanjay-14BIT009** [comment] 2021-11-29 06:06
Thanks for the update. This workaround is working fine, and now I'm able to run the games using Finals2021 boot files. 
For the record: Finals2019 boot-files belong to category-1, and Finals2021 boot-files belong to category-3 of the above comment.

**Comment by jecollins** [comment] 2021-12-15 17:35
Currently, LogtoolCore recycles all the repos and calls DomainObjectReader on all the lines in the log. DomainObjectReader re-creates all the objects whose classnames are not in an "ignores" list. This is not what we want when pulling weather and random-seed data from the log.

- We don't want to recycle repos when mining a state log in the context of starting the server, because that's just been done. Also, if we are pulling both weather and random seeds from state logs, recycling repos a second time will undo work that's already been done.
- Perhaps we need an "includes" list that tells the DOR to only process classes in the list. 
- If we are pulling both weather and random seeds from state logs, it won't work to include both types and just read the state log once, unless the command-line specifies the same state log for both purposes. But doing that check would have to be done in CompetionSetupService, which would otherwise not need to be touched, and we really don't want to add complexity there.

**Comment by jecollins** [comment] 2021-12-17 01:00
WeatherService.StateFileExtractor is used to extract the next n reports and forecasts, where n=24 is the default, after which it closes the file. So for a 60-day session, it opens the file 60 times. Inefficient, yes, but it produces data in blocks just as the web-based version does. But the weather data is stored in WeatherReportRepo and WeatherForecastRepo, and the data that's sent to the brokers and customers appears to come from the repos.

BUT, the repos don't keep all the data, they just keep data from the last 15 days (the length of a boot record). This is an important scalability feature.

On the other hand, it's important to read all the random seeds and populate the RandomSeedRepo at the start of a game. This argues strongly for opening the state log twice even in the case where random seeds and weather data are taken from the same log.

**Comment by jecollins** [comment] 2021-12-18 01:21
Another problem to be solved: when loading seeds, CompetitionSetupService.loadTimeslotCountsMaybe() tries to read the arguments for Competition.withMinimumTimeslotCount() and Competition.withExpectedTimeslotCount() from the log, but without actually creating a Competition and without running those methods on the existing Competition. If we're actually running a boot or sim session, the Competition should have already been created by then and we don't want to replace it. But this info needs to be read through LogtoolCore to support input from URLs and compressed archives. It should be done in the context of reading seeds.

**Comment by jecollins** [comment] 2021-12-18 16:47
CompetitionSetupService.useWeatherDataMaybe() currently accepts a filename ending in .xml or .state. If we want it to accept URLs and archive files, it will need to get the input stream from LogtoolCore. Also, before reading the weather data, useWeatherDataMaybe() extracts the simulationBaseTime from the file. The simulationBaseTime and weather data are coupled.

However, using a weather data stream (and the start time of that weather data) that does not match the end of the boot record may not make sense, because there will be a discontinuity in the weather data, and therefore in weather-related customer and market data, between boot and sim sessions.

**Comment by jecollins** [comment] 2022-01-04 17:52
It turns out RandomSeed is not tagged as an @Domain type, and so object creation is not logged and the DomainObjectReader won't re-create them. The only thing that's logged is the init() call, and the original RandomSeedRepo wasn't even looking at that when it read state logs. This is serious technical debt that needs to be fixed, but in the meantime we'll have to install a kludge, probably in DomainObjectReader, to restore them correctly from old logs.

**Comment by jecollins** [comment] 2022-01-11 18:29
It's now mostly working and merged into the master branch. The only remaining issue is that the way the weather service is initialized, there is now no easy way to get the clock set to the time contained in the weather data.

**Comment by jecollins** [comment] 2022-01-11 23:26
Currently,  seed and weather data sources are processed at the start of a sim session, and domain repos are cleared out at the start of `CSS.preGame()`, much later. This will obviously clear out any seed or weather data that's been acquired prior to that point.

The weather data is processed in `WeatherService.activate()`, at the start of each timeslot, but seed data is processed immediately, at the top of `simSession()`, before the call to `preGame()`. Both are supposed to be able to set the sim clock, but currently `CSS.loadSeedsMaybe()` does it in `simSession()`, and the weather data cannot set the clock because nothing is read from the weather data until after the session is started.

I can see two possible approaches to resolving this -- both depend on moving the code that resets the domain repos to the top of `simSession()`. And we must keep in mind that the seed data must be processed and its file closed before the weather data processing is started, because they may both use the same file, the weather data processing wants to keep the file open throughout the game, and if both are used the weather data must have priority with regard to setting the clock.

1. Modify the weather data processing to find the clock setting info and set the clock before the clock gets set near the top of `CSS.preGame()`.
2. Extract the process of finding the clock settings in a state log to a separate method in CSS that opens the log, finds the Competition instance and waits for it to be populated, and transfers the clock setting to the server config. Obviously this must be done AFTER the config info is collected, which happens in `CSS.setupConfig()`.

**Comment by jecollins** [comment] 2022-01-16 19:16
updated unit tests and system test successful

**Closed by jecollins** 2022-01-16 19:16 UTC
