### ISSUE TITLE
Failed to create queue server-input

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#896] opened 2016-09-14 18:23 UTC
After the refactoring that broke out powertac-parent, there is an error showing up at the start of sample-broker games. The game appears to progress normally, so it's not clear what it means:

250259 ERROR server.JmsManagementService: Failed to create queue serverInput
javax.jms.JMSException: org.apache.activemq.advisory.AdvisorySupport.isVirtualDestinationC
onsumerAdvisoryTopic(Lorg/apache/activemq/command/ActiveMQDestination;)Z
        at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:54
) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1
401) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.apache.activemq.AdvisoryConsumer.<init>(AdvisoryConsumer.java:51) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.apache.activemq.ActiveMQConnection.ensureConnectionInfoSent(ActiveMQConnection.java:1513) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.apache.activemq.ActiveMQConnection.createSession(ActiveMQConnection.java:324) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.springframework.jms.connection.SingleConnectionFactory.createSession(SingleConnectionFactory.java:437) ~[spring-jms-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.jms.connection.CachingConnectionFactory.getSession(CachingConnectionFactory.java:236) ~[spring-jms-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.jms.connection.SingleConnectionFactory$SharedConnectionInvocationHandler.invoke(SingleConnectionFactory.java:604) ~[spring-jms-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at com.sun.proxy.$Proxy194.createSession(Unknown Source) ~[?:?]
        at org.powertac.server.JmsManagementService.createQueue(JmsManagementService.java:174) [server-main-1.4.0-SNAPSHOT.jar!/:1.4.0-SNAPSHOT]
        at org.powertac.server.JmsManagementService.initializeServerQueue(JmsManagementService.java:69) [server-main-1.4.0-SNAPSHOT.jar!/:1.4.0-SNAPSHOT]
        at org.powertac.server.CompetitionControlService.init(CompetitionControlService.java:179) [server-main-1.4.0-SNAPSHOT.jar!/:1.4.0-SNAPSHOT]
        at org.powertac.server.CompetitionControlService.runOnce(CompetitionControlService.java:298) [server-main-1.4.0-SNAPSHOT.jar!/:1.4.0-SNAPSHOT]
        at org.powertac.server.CompetitionSetupService$2.run(CompetitionSetupService.java:579) [server-main-1.4.0-SNAPSHOT.jar!/:1.4.0-SNAPSHOT]
Caused by: java.lang.NoSuchMethodError: org.apache.activemq.advisory.AdvisorySupport.isVirtualDestinationConsumerAdvisoryTopic(Lorg/apache/activemq/command/ActiveMQDestination;)Z
        at org.apache.activemq.advisory.AdvisoryBroker.addConsumer(AdvisoryBroker.java:205) ~[activemq-broker-5.13.4.jar!/:5.13.4]
        at org.apache.activemq.broker.BrokerFilter.addConsumer(BrokerFilter.java:103) ~[activemq-broker-5.13.4.jar!/:5.13.4]
        at org.apache.activemq.broker.BrokerFilter.addConsumer(BrokerFilter.java:103) ~[activemq-broker-5.13.4.jar!/:5.13.4]
        at org.apache.activemq.broker.MutableBrokerFilter.addConsumer(MutableBrokerFilter.java:108) ~[activemq-broker-5.13.4.jar!/:5.13.4]
        at org.apache.activemq.broker.TransportConnection.processAddConsumer(TransportConnection.java:671) ~[activemq-broker-5.13.4.jar!/:5.13.4]
        at org.apache.activemq.command.ConsumerInfo.visit(ConsumerInfo.java:351) ~[activemq-client-5.12.3.jar!/:5.12.3]
        at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:338) ~[activemq-broker-5.13.4.jar!/:5.13.4]

**Comment by erikkemperman** [comment] 2016-09-15 10:56
@jecollins I've tried on several occasions but unable to reproduce this. Could you be more specific what sequence of events lead to this error? E.g., server-distribution or regular viz2? Any special configuration?

**Comment by jecollins** [comment] 2016-09-15 13:13
This was server-distribution after the full deployment, running mvn -Pweb2.

**Comment by jecollins** [comment] 2016-09-15 13:26
It appears that there's a deeper problem. I blew away ~/.m2/repository/org/powertac and then downloaded a fresh copy of server-distribution-master. It cannot find powertac-parent-1.4.0-SNAPSHOT, because (presumably) the [repositories clause was removed](https://github.com/powertac/server-distribution/commit/299ab55e639f4fff74055a900eb6ad9d99c28c9f).

**Comment by erikkemperman** [comment] 2016-09-15 13:33
Yes, we just discovered the same thing here. And also another issue having to do with timestamps in the artifacts on oss. Will fix both ASAP!

**Comment by jecollins** [comment] 2016-09-15 13:42
Yes, I just pushed an update to server-distribution/pom.xml, but that was apparently not enough.

**Comment by jecollins** [comment] 2016-09-15 13:45
Another question: Why does server-distribution now depend on server-interface?

**Comment by erikkemperman** [comment] 2016-09-15 14:35
There is no need for server-interface, and also the scm references were wrong. I cleaned up auctioneer's pom first and then copied bits and pieces of that elsewhere -- it looks suspiciously like I didn't adapt everywhere, the scm references were also wrong.

It's fixed in this PR:
https://github.com/powertac/server-distribution/pull/5/files

**Closed** 2016-10-12 16:46 UTC
